### ISSUE TITLE
Ios 10/11 backups give "Unable to mount this backup because of Invalid Manifest.mbdb magic header"

### ISSUE THREAD

**Issue by arnemoor** [k06a/iBackupMounter#2]
Hi Anton

Trying to load an iOS 10 or 11 backup gives the below error message:
Unable to mount this backup because of Invalid Manifest.mbdb magic header
Loading an old test backup from iOS 7 works.

Does iBackupMounter support current iOS versions?
Cheers, Arne

**Comment by k06a** [comment]
@arnemoor currently working on solution. Apple moved database from Manifest.mbdb to Manifest.db and changed format to SQLite.

**Comment by k06a** [comment]
@arnemoor check `1.1.0` version: https://github.com/k06a/iBackupMounter/releases
Use **iMazing** app (see link in README) to create an unencrypted backups 👍

**Comment by k06a** [comment]
Also discovered @nanotech already added iOS 10/11 support in his fork, great work!
